import DashboardOutlinedIcon from "@mui/icons-material/DashboardOutlined";
import PeopleOutlineIcon from "@mui/icons-material/PeopleOutline";
import Inventory2OutlinedIcon from "@mui/icons-material/Inventory2Outlined";
import AccountTreeOutlinedIcon from "@mui/icons-material/AccountTreeOutlined";
import BookOutlinedIcon from "@mui/icons-material/BookOutlined";
import ReceiptLongOutlinedIcon from "@mui/icons-material/ReceiptLongOutlined";
import ShoppingCartOutlinedIcon from "@mui/icons-material/ShoppingCartOutlined";
import { Box, List, ListItemButton, ListItemIcon, ListItemText, Toolbar, Typography } from "@mui/material";
import { NavLink } from "react-router-dom";

export const drawerWidth = 252;
export const AppSidebar = () => <Box component="aside" sx={{ width: drawerWidth, flexShrink: 0, bgcolor: "primary.dark", color: "primary.contrastText", minHeight: "100vh" }}><Toolbar><Typography variant="h6" fontWeight={800}>URBAN FURNITURE</Typography></Toolbar><Typography variant="overline" sx={{ px: 3, opacity: .65 }}>Workspace</Typography><List sx={{ px: 1 }}><ListItemButton component={NavLink} to="/" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><DashboardOutlinedIcon /></ListItemIcon><ListItemText primary="Dashboard" /></ListItemButton><ListItemButton component={NavLink} to="/contacts" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><PeopleOutlineIcon /></ListItemIcon><ListItemText primary="Contacts" /></ListItemButton><ListItemButton component={NavLink} to="/products" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><Inventory2OutlinedIcon /></ListItemIcon><ListItemText primary="Products" /></ListItemButton><ListItemButton component={NavLink} to="/accounts" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><AccountTreeOutlinedIcon /></ListItemIcon><ListItemText primary="Chart of Accounts" /></ListItemButton><ListItemButton component={NavLink} to="/journals" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><BookOutlinedIcon /></ListItemIcon><ListItemText primary="Journals" /></ListItemButton><ListItemButton component={NavLink} to="/journal-entries" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><ReceiptLongOutlinedIcon /></ListItemIcon><ListItemText primary="Journal Entries" /></ListItemButton><ListItemButton component={NavLink} to="/purchase-orders" sx={{ borderRadius: 2, color: "inherit", "&.active": { bgcolor: "rgba(255,255,255,.14)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 38 }}><ShoppingCartOutlinedIcon /></ListItemIcon><ListItemText primary="Purchase Orders" /></ListItemButton></List></Box>;
