import { api } from "./client";
export type Journal = { id: number; code: string; name: string; type: "SALES" | "PURCHASE" | "CASH" | "BANK" | "GENERAL"; active: boolean };
export type EntryLine = { id: number; accountId: number; debit: string; credit: string; description: string | null; account: { id: number; code: string; name: string; type: string } };
export type JournalEntry = { id: number; entryNumber: string; entryDate: string; referenceType: string | null; referenceId: string | null; description: string | null; status: "DRAFT" | "POSTED"; journal: Journal; lines?: EntryLine[]; _count?: { lines: number } };
export type EntryList = { data: JournalEntry[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };
export const getJournals = async () => (await api.get<{ data: Journal[] }>("/journals")).data.data;
export type JournalEntryFilters = { search?: string; journalId?: number; status?: "DRAFT" | "POSTED"; page: number; pageSize: number };
export const getEntries = async (params: JournalEntryFilters) => (await api.get<EntryList>("/journal-entries", { params: Object.fromEntries(Object.entries(params).filter(([, value]) => value !== undefined && value !== "")) })).data;
export const getEntry = async (id: number) => (await api.get<{ data: JournalEntry }>(`/journal-entries/${id}`)).data.data;
export const postEntry = async (id: number) => (await api.post<{ data: JournalEntry }>(`/journal-entries/${id}/post`)).data.data;
