import type { Prisma } from "@prisma/client";
import { SYSTEM_ACCOUNT_CODES } from "../../config/accounts.js";
import { createAccountingEntryInTransaction } from "../journals/journal.service.js";

type Source = { referenceType: string; referenceId: string; amount: number; date?: Date; description: string };
const accountId = async (tx: Prisma.TransactionClient, code: string) => (await tx.account.findUniqueOrThrow({ where: { code } })).id;
const journalId = async (tx: Prisma.TransactionClient, type: "SALES" | "PURCHASE" | "CASH" | "BANK") => (await tx.journal.findUniqueOrThrow({ where: { type } })).id;

export const createSalesJournalEntry = async (tx: Prisma.TransactionClient, source: Source) => createAccountingEntryInTransaction(tx, { journalId: await journalId(tx, "SALES"), entryDate: source.date ?? new Date(), description: source.description, referenceType: source.referenceType, referenceId: source.referenceId, lines: [{ accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.receivable), debit: source.amount, credit: 0 }, { accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.salesRevenue), debit: 0, credit: source.amount }] }, true, true);
export const createCustomerPaymentJournalEntry = async (tx: Prisma.TransactionClient, source: Source) => createAccountingEntryInTransaction(tx, { journalId: await journalId(tx, "BANK"), entryDate: source.date ?? new Date(), description: source.description, referenceType: source.referenceType, referenceId: source.referenceId, lines: [{ accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.bank), debit: source.amount, credit: 0 }, { accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.receivable), debit: 0, credit: source.amount }] }, true, true);
export const createPurchaseJournalEntry = async (tx: Prisma.TransactionClient, source: Source) => createAccountingEntryInTransaction(tx, { journalId: await journalId(tx, "PURCHASE"), entryDate: source.date ?? new Date(), description: source.description, referenceType: source.referenceType, referenceId: source.referenceId, lines: [{ accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.purchaseExpense), debit: source.amount, credit: 0 }, { accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.payable), debit: 0, credit: source.amount }] }, true, true);
export const createVendorPaymentJournalEntry = async (tx: Prisma.TransactionClient, source: Source) => createAccountingEntryInTransaction(tx, { journalId: await journalId(tx, "BANK"), entryDate: source.date ?? new Date(), description: source.description, referenceType: source.referenceType, referenceId: source.referenceId, lines: [{ accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.payable), debit: source.amount, credit: 0 }, { accountId: await accountId(tx, SYSTEM_ACCOUNT_CODES.bank), debit: 0, credit: source.amount }] }, true, true);
