import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { ThemeProvider } from "@mui/material/styles";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { App } from "./App";
import { AuthProvider } from "./features/auth/AuthProvider";
import { theme } from "./theme";
const queryClient = new QueryClient();
createRoot(document.getElementById("root")!).render(<StrictMode><QueryClientProvider client={queryClient}><ThemeProvider theme={theme}><BrowserRouter><AuthProvider><App /></AuthProvider></BrowserRouter></ThemeProvider></QueryClientProvider></StrictMode>);
